version: "3"

services:
    nginx:
      build: ./nginx
      container_name: nginx-account
      restart: always
      ports: 
        - 82:82
      depends_on:
        - account
      networks:
        - backend
    account:
      build: ./
      restart: always
      volumes: 
        - ./account/:/go/src/github.com/microservices/services/account
      container_name: account
      ports: 
        - 9092:9092
      networks:
        - backend
      depends_on:
        - dbaccount
      links:
        - dbaccount
      environment:
        - DATABASE_HOST=dbaccount
        - DATABASE_USER=postgres
        - DATABASE_PASS=postgressecret
        - DATABASE_PORT=5432
        - DATABASE_NAME=microservices
        - SERVER_ADDRESS=:9092
    dbaccount:
      image: postgres:12.2-alpine
      container_name: pgsql-account
      restart: always
      environment:
        POSTGRES_DB: microservices
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgressecret
      volumes:
        - pgdata:/var/lib/postgresql/data
      shm_size: '4gb'
      expose: 
        - 5432  
      networks:
        - backend
    dbbrowser:
      restart: on-failure
      image: adminer:4-standalone
      container_name: db-browser-account
      ports:
        - "18082:8080"
      depends_on:
        - dbaccount
      links:
        - dbaccount
      networks:
        - backend
      logging:
        driver: none
      environment:
        - ADMINER_DEFAULT_SERVER=dbaccount
        - ADMINER_DESIGN=flat
  
networks:
    backend:
  
volumes:
    pgdata: