version: "3"

services:
    nginx:
      build: ./nginx
      container_name: nginx-product
      restart: always
      ports: 
        - 81:81
      depends_on:
        - product
      networks:
        - backend
    product:
      build: ./
      restart: always
      volumes: 
        - ./product/:/go/src/github.com/microservices/services/product
      container_name: product
      ports: 
        - 9091:9091
      networks:
        - backend
      depends_on:
        - dbproduct
      links:
        - dbproduct
      environment:
        - DATABASE_HOST=dbproduct
        - DATABASE_USER=postgres
        - DATABASE_PASS=postgressecret
        - DATABASE_PORT=5432
        - DATABASE_NAME=microservices
        - SERVER_ADDRESS=:9091
    dbproduct:
      image: postgres:12.2-alpine
      container_name: pgsql-product
      restart: always
      environment:
        POSTGRES_DB: microservices
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgressecret
      volumes:
        - pgdata:/var/lib/postgresql/data
      shm_size: '4gb'
      expose: 
        - 5432  
      networks:
        - backend
    dbbrowser:
      restart: on-failure
      image: adminer:4-standalone
      container_name: db-browser-product
      ports:
        - "18080:8080"
      depends_on:
        - dbproduct
      links:
        - dbproduct
      networks:
        - backend
      logging:
        driver: none
      environment:
        - ADMINER_DEFAULT_SERVER=dbproduct
        - ADMINER_DESIGN=flat
  
networks:
    backend:
  
volumes:
    pgdata: